### ISSUE TITLE
Incorrect time stamp of TF

### ISSUE THREAD

**Issue by yangweiyou** [ADVRHumanoids/tutorial_iros2018#10]
When I launch reemc_gazebo, the robot is able to show up in Gazebo and the SimpleHoming plugin can work. But the time stamp of TF is always 29s, like below:
  - 
    header: 
      seq: 0
      stamp: 
        secs: 29
        nsecs:         0
      frame_id: "leg_left_1_link"
    child_frame_id: "leg_left_2_link"
    transform: 
      translation: 
        x: 0.0
        y: 0.0
        z: 0.0
      rotation: 
        x: 0.00140485912832
        y: 0.707105385617
        z: 0.00140485912832
        w: 0.70710538562

So rviz keeps complaining about this.
We tried on two computers, one is okay and another one has this problem.
Do you have any clue what the reason can be?

**Comment by liesrock** [comment]
Hi @yangweiyou this depends on the ROS version you are using: unfortunately in the latest update they introduced an bug in the rostime library.
This unfortunately does not depend on us.

**Comment by yangweiyou** [comment]
Got it. Thanks, Luca!

**Comment by yangweiyou** [comment]
The similar issue happened to Centauro robot. The TF timestamp published by XBotControl is not consistent with ROS time. So when trying to publish an odometric TF with current ROS time, RVIZ complaints about this. Is there any good way to address this? Or any compatible ROS and Gazebo version to recommend?

**Comment by liesrock** [comment]
Bringing back the roscpp_core to 0.6.9 from sources and installing them in /opt/ros/kinetic lead to a set of errors even when using ROS basic tools as roscore.

**Comment by liesrock** [comment]
Even using the default sensor_msgs::JointState inside a library (JointStateRemapper) of the XBotControl package leads to a fixed time with different values this time:
```   
    header: 
      seq: 0
      stamp: 
        secs: 2952823976
        nsecs:     32759
 ```

**Comment by liesrock** [comment]
The standard ros joint_state_publisher and robot_state_publisher are working. I will investigate the issue on the linking of our internal robot_state_publisher and roscpp libraries and release a new version ASAP @alaurenzi .

**Comment by liesrock** [comment]
The issue should be fixed in the latest release:  https://github.com/ADVRHumanoids/XBotControl/releases/download/v1.0.1/XBotControl_1.0-1.deb

Tested on two different machines with the latest ROS: please double check when you can and let us know.
