### ISSUE TITLE
Tutorial Documentation

### ISSUE THREAD

**Issue by williamalexmoran** [ADVRHumanoids/tutorial_iros2018#11]
Hi all, 
I am trying to run through tutorials, but am having trouble following what to do. Is there step by step documentation for the tutorial? any help would be greatly appreciated!

**Comment by liesrock** [comment]
Hi @williamalexmoran, welcome to the XBot tutorial repo! 
We tried to document each componet of the tutorial using a jupiter notebook: try to go in the code and follow the instruction in the file with extension .ipynb inside each subfolder (e.g. Configs)

**Comment by williamalexmoran** [comment]
Do i have to run cmake on this project? When i do run it, I get this error

CMake Error at plugins/GcompPlugin/CMakeLists.txt:43 (find_package):
  By not providing "FindXCM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "XCM", but
  CMake did not find one.

  Could not find a package configuration file provided by "XCM" with any of
  the following names:

    XCMConfig.cmake
    xcm-config.cmake

  Add the installation prefix of "XCM" to CMAKE_PREFIX_PATH or set "XCM_DIR"
  to a directory containing one of the above files.  If "XCM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!

**Comment by williamalexmoran** [comment]
nevermind, sourcing before running cmake was necessary.

**Comment by williamalexmoran** [comment]
I am now getting this error while compiling
/home/gizmo/Documents/XBotControlTutorial/tutorial_iros2018-8ccd4b18b14cca7313c5d49c493ac27e374334dc/opensot/include/IDProblem.h:11:43: fatal error: OpenSoT/utils/InverseDynamics.h: No such file or directory
I checked the OpenSot/utils folder, and it does not have InverDynamics.h. is this something i am supposed to fetch on my on and manually place in OpenSot?

**Comment by liesrock** [comment]
Did you install XBotControl following the instructions here: https://github.com/ADVRHumanoids/XBotControl/blob/master/README.md

Give us some feedback on the instructions if possible.

Do you work in the humanoids robotics field? In which part of the framework are you more interested?

**Comment by williamalexmoran** [comment]
I followed the instructions and installed XBotControl. I am working with Virginia Tech in their terrestrial robotics engineering and controls lab. We were thinking about using XBotControl for our humanoid robot.

**Comment by williamalexmoran** [comment]
maybe an addition in the main folder with instructions on how to begin the tutorial, such as making the projects, and which portions to go through first might also be helpful.

**Comment by liesrock** [comment]
Ok thanks a lot for your feedback: maybe also @alaurenzi and @enricomingo can help!

**Comment by williamalexmoran** [comment]
No problem! i am excited to see where XBotControl goes! Any suggestions on the missing InverDynamics.h?

**Comment by liesrock** [comment]
@williamalexmoran I am on it! I will update you asap

**Comment by liesrock** [comment]
Hi @williamalexmoran, thanks for your patience: I solved the issue in bec84b87807aa655b6bc72be82d26c6c89a6ca1b with a new branch called v1.0.0 which is compatible with the current binary version released.

I also tried to follow your suggestion adding some details in the readme (https://github.com/ADVRHumanoids/tutorial_iros2018#tutorial-iros-2018) about how to follow the tutorial : please give me a feedback (it would be useful also from @FrancescoRuscelli ).

We are currently working to have the v1.0.1 released with the ID integration.

**Comment by williamalexmoran** [comment]
Hi @liesrock, Thank you so much for putting out an updated tutorial. One quick bug, on the tutorial install guide, there is an extra git clone. this line in particular "git clone git clone https://github.com/ADVRHumanoids/tutorial_iros2018.git -b v1.0.0". again thank you so much for updating this!

**Comment by liesrock** [comment]
Thanks again to you @williamalexmoran : give us update when you have time J

**Comment by williamalexmoran** [comment]
Will do! going through some of the tutorial now! Is the tutorial's launch section finished? could i run roslaunch tutorial_iros2018 reemc_slider.launch and then rviz -d reemc_slider.rviz? or is that not currently implemented?

**Comment by liesrock** [comment]
Everthing documented is implemented! Please go ahead.
