### ISSUE TITLE
Launch section of the iros_tutorial and Fixed Frame [map] does not exist error

### ISSUE THREAD

**Issue by williamalexmoran** [ADVRHumanoids/tutorial_iros2018#12]
Hi all, i am trying to launch reemc_slider.launch. It successfully launches, using roslaunch tutorial_iros2018 reemc_slider.launch. once it launches i try to run the rviz -d reemc_slider.rviz command given in the tutorial. it opens rviz, but there is no robot, and in the global status section i get the error Fixed Frame [map] does not exist error.

**Comment by liesrock** [comment]
HI @williamalexmoran do you have some basic knowledge of the ROS TF mechanism and the Rviz basic usage? Please have a look on the ROS tutorial documentation in case, but in general you should select from the fixed frame list in Rviz and existing frame name.

**Comment by liesrock** [comment]
I think we can close this since it is not related to our framework.
